# base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: registration-app
  template:
    metadata:
      labels:
        app: registration-app
    spec:
      containers:
      - name: registration-app
        image: nabi22446688/registration-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /registrations
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /registrations
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
