# base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: registration-app
  namespace: prod
spec:
  selector:
    app: registration-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
